var linkEditorStr = '<div id="linkeditor" class="ui-widget-header ui-state-default ui-corner-all">'
        + '<div id="linkmenu" class="ui-widget-header">Link Editor<span class="icon-remove" id="linkclose" ></span>'
        + '<span class="icon-thumbs-up" id="linkrecom" ></span></div><label class="label">Paste many links at once</label> Ctrl+V'
        + '<div style="height:100px; background-color:#fff" contenteditable="true" id="linkpaste"></div>'
        + '<span id="linkpastesave" class="btn btn-small btn-info" title="Save all the links in paste">Save the paste</span>'
        + '<span id="linkpasteclear" class="btn btn-small btn-warning" title="Clear the paste">Clear</span>'
        + '<div class="clear"></div>'
        + '<label class="label">title</label>'
        + '<input type="text" id="linktitle" >'
        + '<label class="label">url</label>'
        + '<input type="text" id="linkhref" >'
        + '<label class="label">icon</label>'
        + '<input type="text" id="linkicon" >'
        + '<label class="label">memo</label>'
        + '<textarea id="linkmemo" ></textarea>'
        + '<span id="linksave" class="btn btn-small btn-primary" title="Save and finish editting">save</span>'
        + '<span id="linkapply" class="btn btn-small btn-warning" title="Apply and continue editting">apply</span>'
        + '<span id="linkcancel" class="btn btn-small" title="Cancel the editting">cncl</span>'
        + '<span id="linkdel" class="btn btn-small btn-danger" title="Delete the link">del</span>'
        + '</div>';

var folderEditorStr = '<div id="foldereditor" class="ui-widget-header ui-state-default ui-corner-all">'
        + '<div id="foldermenu" class="ui-widget-header">Folder Editor'
        + '<span class="icon-remove" id="folderclose" ></span>'
        + '<span class="icon-thumbs-up" id="folderrecom"></span>'
        + '</div>'
        + '<label class="label">title</label>'
        + '<input  type="text" id="folderhead" >'
        + '<label class="label">icon</label><span class="icon-picture" id="foldericonshow" ></span><span class="icon-remove" id="foldericonremove" ></span><span id="foldericonpreview"></span>'
        + '<input  type="text" id="foldericon" >'
        + '<label class="label">memo</label>'
        + '<textarea  id="foldermemo" ></textarea>'
        + '<span class="icon-chevron-down" id="foldermore"></span>'
        + '<span class="icon-chevron-up" id="folderless"></span>'
        + '<div class="clear"></div>'
        + '<div id="foldermoremenu">'
        + '<label class="label">bg image</label>'
        + '<input  type="text" id="bgimage" >'
        + '<label class="label">bg position</label>'
        + '<select  id="bgposition" >'
        + '<option value="center center">center center</option>'
        + '<option value="right center">right center</option>'
        + '<option value="right top">right top</option>'
        + '<option value="right bottom">right bottom</option>'
        + '<option value="left center">left center</option>'
        + '<option value="left top">left top</option>'
        + '<option value="left bottom">left bottom</option>'
        + '</select>'
        + '<label class="label">bg repeat</label>'
        + '<select  id="bgrepeat" >'
        + '<option value="no-repeat">no-repeat</option>'
        + '<option value="repeat">repeat</option>'
        + '<option value="repeat-x">repeat-x</option>'
        + '<option value="repeat-y">repeat-y</option>'
        + '</select>'
        + '<label class="label">bg color ( #ffffff or rgba())</label>'
        + '<input  type="text" id="bgcolor" >'
        + '<label class="label">link view type</label>'
        + '<select  id="linkviewtype" >'
        + '<option value="2">icon + text</option>'
        + '<option value="3">text only</option>'
        + '<option value="0">image + text</option>'
        + '<option value="1">image only</option>'
        + '</select>'
        + '</div>'
        + '<span id="foldersave" class="btn btn-small btn-primary" title="Save and finish editting">save</span>'
        + '<span id="folderapply" class="btn btn-small btn-warning" title="Apply and continue editting">apply</span>'
        + '<span id="foldercancel" class="btn btn-small " title="Cancel the editting">cncl</span>'
        + '<span id="folderdel" class="btn btn-small btn-danger" title="Delete this folder">del</span>'
        + '</div>';

var widgetIconTableStr = '<div id="widgeticontable">'
        + '<span class="icon-remove" id="foldericonhide" style="float:right; margin-right:15px; margin-top:5px"></span>'
        + '<div class="clear"></div>'
        + '<div ng-click="selectIcon($event)" >'
        + '<div class="trow">'
        + '<div class="wicon0"></div>'
        + '<div class="wicon1"></div>'
        + '<div class="wicon2"></div>'
        + '<div class="wicon3"></div>'
        + '<div class="wicon4"></div>'
        + '<div class="wicon5"></div>'
        + '<div class="wicon6"></div>'
        + '<div class="wicon7"></div>'
        + '<div class="wicon8"></div>'
        + '<div class="wicon9"></div>'
        + '<div class="wicon10"></div>'
        + '<div class="wicon11"></div>'
        + '<div class="wicon12"></div>'
        + '<div class="wicon13"></div>'
        + '<div class="wicon14"></div>'
        + '<div class="wicon15"></div>'
        + '</div>'
        + '<div class="trow">'
        + '<div class="wicon16"></div>'
        + '<div class="wicon17"></div>'
        + '<div class="wicon18"></div>'
        + '<div class="wicon19"></div>'
        + '<div class="wicon20"></div>'
        + '<div class="wicon21"></div>'
        + '<div class="wicon22"></div>'
        + '<div class="wicon23"></div>'
        + '<div class="wicon24"></div>'
        + '<div class="wicon25"></div>'
        + '<div class="wicon26"></div>'
        + '<div class="wicon27"></div>'
        + '<div class="wicon28"></div>'
        + '<div class="wicon29"></div>'
        + '<div class="wicon30"></div>'
        + '<div class="wicon31"></div>'
        + '</div>'
        + '<div class="trow">'
        + '<div class="wicon32"></div>'
        + '<div class="wicon33"></div>'
        + '<div class="wicon34"></div>'
        + '<div class="wicon35"></div>'
        + '<div class="wicon36"></div>'
        + '<div class="wicon37"></div>'
        + '<div class="wicon38"></div>'
        + '<div class="wicon39"></div>'
        + '<div class="wicon40"></div>'
        + '<div class="wicon41"></div>'
        + '<div class="wicon42"></div>'
        + '<div class="wicon43"></div>'
        + '<div class="wicon44"></div>'
        + '<div class="wicon45"></div>'
        + '<div class="wicon46"></div>'
        + '<div class="wicon47"></div>'
        + '</div>'
        + '<div class="trow">'
        + '<div class="wicon48"></div>'
        + '<div class="wicon49"></div>'
        + '<div class="wicon50"></div>'
        + '<div class="wicon51"></div>'
        + '<div class="wicon52"></div>'
        + '<div class="wicon53"></div>'
        + '<div class="wicon54"></div>'
        + '<div class="wicon55"></div>'
        + '<div class="wicon56"></div>'
        + '<div class="wicon57"></div>'
        + '<div class="wicon58"></div>'
        + '<div class="wicon59"></div>'
        + '<div class="wicon60"></div>'
        + '<div class="wicon61"></div>'
        + '<div class="wicon62"></div>'
        + '<div class="wicon63"></div>'
        + '</div>'
        + '<div class="trow">'
        + '<div class="wicon64"></div>'
        + '<div class="wicon65"></div>'
        + '<div class="wicon66"></div>'
        + '<div class="wicon67"></div>'
        + '<div class="wicon68"></div>'
        + '<div class="wicon69"></div>'
        + '<div class="wicon70"></div>'
        + '<div class="wicon71"></div>'
        + '<div class="wicon72"></div>'
        + '<div class="wicon73"></div>'
        + '<div class="wicon74"></div>'
        + '<div class="wicon75"></div>'
        + '<div class="wicon76"></div>'
        + '<div class="wicon77"></div>'
        + '<div class="wicon78"></div>'
        + '<div class="wicon79"></div>'
        + '</div>'
        + '<div class="trow">'
        + '<div class="wicon80"></div>'
        + '<div class="wicon81"></div>'
        + '<div class="wicon82"></div>'
        + '<div class="wicon83"></div>'
        + '<div class="wicon84"></div>'
        + '<div class="wicon85"></div>'
        + '<div class="wicon86"></div>'
        + '<div class="wicon87"></div>'
        + '<div class="wicon88"></div>'
        + '<div class="wicon89"></div>'
        + '<div class="wicon90"></div>'
        + '<div class="wicon91"></div>'
        + '<div class="wicon92"></div>'
        + '<div class="wicon93"></div>'
        + '<div class="wicon94"></div>'
        + '<div class="wicon95"></div>'
        + '</div>'
        + '<div class="trow">'
        + '<div class="wicon96"></div>'
        + '<div class="wicon97"></div>'
        + '<div class="wicon98"></div>'
        + '<div class="wicon99"></div>'
        + '<div class="wicon100"></div>'
        + '<div class="wicon101"></div>'
        + '<div class="wicon102"></div>'
        + '<div class="wicon103"></div>'
        + '<div class="wicon104"></div>'
        + '<div class="wicon105"></div>'
        + '<div class="wicon106"></div>'
        + '<div class="wicon107"></div>'
        + '<div class="wicon108"></div>'
        + '<div class="wicon109"></div>'
        + '<div class="wicon110"></div>'
        + '<div class="wicon111"></div>'
        + '</div>'
        + '<div class="trow">'
        + '<div class="wicon112"></div>'
        + '<div class="wicon113"></div>'
        + '<div class="wicon114"></div>'
        + '<div class="wicon115"></div>'
        + '<div class="wicon116"></div>'
        + '<div class="wicon117"></div>'
        + '<div class="wicon118"></div>'
        + '<div class="wicon119"></div>'
        + '<div class="wicon120"></div>'
        + '<div class="wicon121"></div>'
        + '<div class="wicon122"></div>'
        + '<div class="wicon123"></div>'
        + '<div class="wicon124"></div>'
        + '<div class="wicon125"></div>'
        + '<div class="wicon126"></div>'
        + '<div class="wicon127"></div>'
        + '</div>'
        + '<div class="trow">'
        + '<div class="wicon128"></div>'
        + '<div class="wicon129"></div>'
        + '<div class="wicon130"></div>'
        + '<div class="wicon131"></div>'
        + '<div class="wicon132"></div>'
        + '<div class="wicon133"></div>'
        + '<div class="wicon134"></div>'
        + '<div class="wicon135"></div>'
        + '<div class="wicon136"></div>'
        + '<div class="wicon137"></div>'
        + '<div class="wicon138"></div>'
        + '<div class="wicon139"></div>'
        + '<div class="wicon140"></div>'
        + '<div class="wicon141"></div>'
        + '<div class="wicon142"></div>'
        + '<div class="wicon143"></div>'
        + '</div>'
        + '</div>'
        + '<div id="wiconsetting">Set your own<div class="clear"></div>'
        + '<label class="label">icon url</label>'
        + '<input type="url" name="iconurl" id="iconurl" placeholder="widget icon url" ng-model="widget.iconurl">'
        + '<label class="label">icon data</label>'
        + '<input type="text" name="icondata" id="icondata" placeholder="widget icon data in base64" ng-model="widget.icondata">'
        + '</div>'
        + '</div>';

var pageEditorStr = '<div id="pageeditor" class="ui-widget-header ui-state-default ui-corner-all">'
        + '<div id="pageeditormenu" class="ui-widget-header">Page Editor'
        + '<span class="icon-remove" id="pageclose" ></span>'
        + '<span class="icon-thumbs-up" id="pagerecom"></span>'
        + '</div>'
        + '<label class="label">title</label>'
        + '<input  type="text" id="pagetitle" name="pagetitle">'
        + '<label class="label">page theme</label>'
        + '<select  id="pagetheme" >'
        + '<option value="black-tie">black-tie</option>'
        + '<option value="blitzer">blitzer</option>'
        + '<option value="bullet-arrow">bullet-arrow</option>'
        + '<option value="cupertino">cupertino</option>'
        + '<option value="dark-hive">dark-hive</option>'
        + '<option value="dot-luv">dot-luv</option>'
        + '<option value="eggplant">eggplant</option>'
        + '<option value="excite-bike">excite-bike</option>'
        + '<option value="flick">flick</option>'
        + '<option value="hot-sneaks">hot-sneaks</option>'
        + '<option value="humanity">humanity</option>'
        + '<option value="iphone">iphone</option>'
        + '<option value="le-frog">le-frog</option>'
        + '<option value="mint-choc">mint-choc</option>'
        + '<option value="nested">nested</option>'
        + '<option value="overcast">overcast</option>'
        + '<option value="pepper-grinder">pepper-grinder</option>'
        + '<option value="redmond">redmond</option>'
        + '<option value="rotated">rotated</option>'
        + '<option value="smoothness">smoothness</option>'
        + '<option value="south-street">south-street</option>'
        + '<option value="start">start</option>'
        + '<option value="sunny">sunny</option>'
        + '<option value="swanky-purse">swanky-purse</option>'
        + '<option value="trontastic">trontastic</option>'
        + '<option value="overcast">overcast</option>'
        + '<option value="ui-darkness">ui-darkness</option>'
        + '<option value="ui-lightness">ui-lightness</option>'
        + '<option value="vader">vader</option>'
        + '</select>'
        + '<span class="icon-chevron-down" id="pagemore"></span>'
        + '<span class="icon-chevron-up" id="pageless"></span>'
        + '<div class="clear"></div>'
        + '<div id="pagemoremenu">'
        + '<label class="label">bg image</label>'
        + '<input  type="text" id="pagebgimage" >'
        + '<label class="label">bg image(mobile)</label>'
        + '<input  type="text" id="pagebgimagea" >'
        + '<label class="label">bg position</label>'
        + '<select  id="pagebgposition" >'
        + '<option value="center center">center center</option>'
        + '<option value="right center">right center</option>'
        + '<option value="right top">right top</option>'
        + '<option value="right bottom">right bottom</option>'
        + '<option value="left center">left center</option>'
        + '<option value="left top">left top</option>'
        + '<option value="left bottom">left bottom</option>'
        + '</select>'
        + '<label class="label">bg repeat</label>'
        + '<select  id = "pagebgrepeat" >'
        + '<option value="no-repeat">no-repeat</option>'
        + '<option value="repeat">repeat</option>'
        + '<option value="repeat-x">repeat-x</option>'
        + '<option value="repeat-y">repeat-y</option>'
        + '</select>'
        + '<label class="label">bg color ( #ffffff or rgba())</label>'
        + '<input  type="text" id="pagebgcolor" >'
        + '<label class="label">bg color(mobile) ( #ffffff or rgba())</label>'
        + '<input  type="text" id="pagebgcolora" >'
        + '<label class="label">page theme</label>'
        + '</div>'
        + '<span id="pagesave" class="btn btn-small btn-primary" title="Save and finish config editting">save</span>'
        + '<span id="pageapply" class="btn btn-small btn-warning" title="Apply and continue config editting">apply</span>'
        + '<span id="pagecancel" class="btn btn-small " title="Cancel the config editting">cncl</span>'
        + '<span id="pagedel" class="btn btn-small btn-danger" title="Delete this page config">del</span>'
        + '</div>';

var pageToolsStr = '<div id="pagetools" class="ui-widget-header ui-state-default ui-corner-all">'
        + '<div class="handle">'
        + '<div id="linkmenu" class="ui-widget-header">Page Tools'
        + '<span class="icon-remove" id="closetools" ></span>'
        + '</div>'
        + '<label class="label">Bookmarket to catch URL</label>'
        + '<p>Bookmarklet is used to easily catch URL of the site you visit.</p>'
        + '<p>Drag and drop the below bookmarklet onto your browser menubar.</p>'
        + '</div>'
        + '<div class="clear"></div>'
        + '<a  id="bookmarklet" class="btn btn-large btn-info" href="javascript:var d=document,w=window,e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:\'\')),l=d.location,e=encodeURIComponent,u=e(l.href)+\'&\'+e(d.title)+\'&\'+e(s);w.prompt(\'Copy to clipboard: Ctrl+C, Enter\', u);void(0)">Bookmarklet</a>'
        + '<hr>'
        + '<div class="handle" style="min-height: 20px">'
        + '<label class="label">Other useful tools</label>'
        + '<span id="addhomefolder" class="btn btn-small" title="Add home folder">Create New Folder</span>'
        + '<span id="showremovefavicons" class="btn btn-small" title="Remove the dead favicons indicated below">Remove the dead favicons</span>'
        + '<span id="showimporter" class="btn btn-small" title="Import bookmark html into folders">Import bookmark</span>'
        + '<span id="showexporter" class="btn btn-small" title="export folders into bookmark html">export bookmark</span>'
        + '</div>'
        + '</div>';

var messengerStr = '<div id="message" class="ui-corner-all"></div>'
        + '<div id="errormessage" class="ui-corner-all"></div>';

var importerStr = '<div class="center" id="importer">'
        + '<div id="importermenu">'
        + '  Bookmark import or export ( To import, click "processimporter", "importfolders" buttons in series )'
        + '<label class="label" >For favicons:</label><span class="btn btn-small" id="removefavicons" title="Remove favicons indicated below."><span class="icon-remove-circle"></span></span>'
        + '<label class="label" id="exportlabel">For export:</label><span class="btn btn-small btn-primary" id="exportfolders" title="exportfolders to export folders into bookmark html file."><span class="icon-share"></span></span>'
        + '<span class="icon-remove" id="closeimporter" title="Close this importer"></span>'
//        + '<span class="btn btn-small" id="importfolders" title="importfolders to import folders processed."><span class="icon-share"></span></span>'
        + '<span class="btn btn-small btn-warning" id="processimporter" title="processimporter to process the source to make folders."><span class="icon-retweet"></span></span>'
        + '<label class="label" id="importlabel">For import:</label>'
        + '</div>'
        + '<div contenteditable="true" id="importersource"></div>'
        + '</div>';

var editors = linkEditorStr + folderEditorStr + widgetIconTableStr + pageEditorStr + pageToolsStr + messengerStr + importerStr;